version: '2'
services:
  api:
    env_file: .env
    build: ./api
#    ports:
#      - "8001:8080"
    # links:
    #   - "redis:redis"
    #   - "mongodb:mongodb"
  administration:
    env_file: .env
    build: ./administration
 #   ports:
 #     - "8000:8080"
    # links:
    #   - "redis:redis"
    #   - "api:api"
    #   - "mongodb:mongodb"
  redis:
    image: redis
  mongodb:
    image: mongo:3.2
#    ports:
#     - "27017:27017"
    command: mongod --smallfiles --rest --noauth

